
package br.com.globus.service;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegracaoVelocimetroWSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegracaoVelocimetroWSSoap {


    /**
     * Retorna informações de abastecimento agrupados por chassi e veículo
     * 
     * @param prefixo
     * @param dataHora
     * @param placa
     * @param hodometro
     * @return
     *     returns br.com.globus.service.ArrayOfString
     */
    @WebMethod(operationName = "AtualizarVelocimetro", action = "http://tempuri.org/AtualizarVelocimetro")
    @WebResult(name = "AtualizarVelocimetroResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AtualizarVelocimetro", targetNamespace = "http://tempuri.org/", className = "br.com.globus.service.AtualizarVelocimetro")
    @ResponseWrapper(localName = "AtualizarVelocimetroResponse", targetNamespace = "http://tempuri.org/", className = "br.com.globus.service.AtualizarVelocimetroResponse")
    public ArrayOfString atualizarVelocimetro(
        @WebParam(name = "prefixo", targetNamespace = "http://tempuri.org/")
        String prefixo,
        @WebParam(name = "placa", targetNamespace = "http://tempuri.org/")
        String placa,
        @WebParam(name = "dataHora", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dataHora,
        @WebParam(name = "hodometro", targetNamespace = "http://tempuri.org/")
        BigDecimal hodometro);

}
